image: vineethvinni/devops_agent:v1

variable:
  sonar_url: http://3.83.151.11:9000
  sonar_token: ${sonar_token}
before_script:
  - cd java-maven-sonar-argocd-helm-k8s/sprint-boot-app
stages
  - build
  - test
  - sonarqube
  - docker
build:
  stage: build
  script:
    - mvn clean package
test:
  stage: test
  sript:
    - mvn test
sonar_qube:
  stage: sonarqube
  script:
    - mvn sonar:sonar -Dsonarurl=${sonar_url} -Dsonar-token=${sonar_token}
