image: 'abhishekf5/maven-abhishek-docker-agent:v1'

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''
  #sonar_url: http://3.83.151.11:9000
  #sonar_token: ${sonar_token}
  NEXUS_RELEASES_URL: http://3.83.151.11:8081/repository/cicd/
  NEXUS_SNAPSHOTS_URL: http://3.83.151.11:8081/repository/cicd_snapshot/
  IMAGE_NAME: vineethvinni/cicd
  IMAGE_TAG: $CI_PIPELINE_ID
  DOCKERHUB_PASSWORD: ${CI_REGISTRY_PASSWORD}
  DOCKERHUB_USERNAME: ${CI_REGISTRY_USER}

before_script:
  - cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
stages:
  - build
  - test
  - sonarqube
  - nexus_deploy
  - docker_build
build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      # This saves your compiled jar so future stages can use it
      - java-maven-sonar-argocd-helm-k8s/spring-boot-app/target/
test:
  stage: test
  script:
    - mvn test
sonar_qube:
  stage: sonarqube
  script:
    - if [ -z "$sonar_token" ]; then echo "sonar_token is EMPTY"; else echo "sonar_token is SET"; fi
    - mvn sonar:sonar -Dsonar.host.url=http://3.83.151.11:9000 -Dsonar.login=${sonar_token}
nexus_deploy:
  stage: nexus_deploy
  dependencies:
    # This downloads the jar from the build stage
    - build
  script:
    - |
      echo "<settings>
        <servers>
          <server>
            <id>nexus-releases</id>
            <username>${NEXUS_USER}</username>
            <password>${NEXUS_PASSWORD}</password>
          </server>
          <server>
            <id>nexus-snapshots</id>
            <username>${NEXUS_USER}</username>
            <password>${NEXUS_PASSWORD}</password>
          </server>
        </servers>
      </settings>" > ci-settings.xml
    - mvn deploy -s ci-settings.xml -DaltReleaseDeploymentRepository=nexus-releases::default::${NEXUS_RELEASES_URL} -DaltSnapshotDeploymentRepository=nexus-snapshots::default::${NEXUS_SNAPSHOTS_URL}
  only:
    - main
docker_build:
  stage: docker_build
  image: docker:19.03     
  services:
    - name: docker:dind  
  dependencies:
    - build
  script:
    # Login, build, and push using your specified environment variables
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}
    #- docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:${IMAGE_TAG}
    - 'sed -i "s|image: vineethvinni/cicd:latest|image: ${IMAGE_NAME}:${IMAGE_TAG}|g" ../../java-maven-sonar-argocd-helm-k8s/k8/deployment.yaml'
  only:
    - main