apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: ghcr.io/vijayakhil13/sample_springboot_application-deployed_in_k8_using_gitlab:635a8df
        ports:
        - containerPort: 8090